spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    com:
      google:
        firebase: info
  file:
    name: ../logs/springApp.log

firebase:
  StorageBucketUrl: 'projectai-4361d.appspot.com'
  authUrl: 'https://identitytoolkit.googleapis.com/v1'
  authKey: 'AIzaSyDdro-Gy2WE7Xf1-capRrKNrU0pQdA0Gkg'

segmid:
  url: 'https://api.segmind.com'
