spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

segmidToken: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDYyNzI4NjIsIm5iZiI6MTcwNjI3Mjg2MiwianRpIjoiMTU2N2FkYjUtMDMzMS00NjgwLWFkZjUtNWI2MzcyNWZlYmM5IiwiZXhwIjoxNzA2MzU5MjYyLCJpZGVudGl0eSI6InNocnV0aGlyZWRkeTE3MjlAZ21haWwuY29tIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.KDJ6nEcpt7aGS0tWV7l5wZrqH95qwPR4cpXVVBa9nsQXhsmXlZhgVHI6GLe5wubRGdvgkLUhjmDkP0Krl-ZExBh9OVm2q3AJPiR2zajeOUtWOJ6-jxQQQZhc4p9RPDYyQxQf-UlNy8Y7clIx61rc9f4EopRyLt9qIXC1GBIOsFAtrk8wT4cYKh9CWvNVS6niUrm9urxW_3g9apqwR_WsT7BrIHCYbW1EsovNpj0U3OtEw_A4xBPr1GDJQ_udTzcBgNPOoO9mEyd9JoP3xJEmspn2oBlRanyiqkpErAUumSnV0Ic6cKC1jpyZRR_4g91sWhBvI_Jc_wTUI2kCSzOzA-5JdWHnYiAFx0tClXzqgmON9nOV0c9qo5grs1XVtsTH9ftGqDa0js2dSoc94Z37IjWp3tHxkl01_6V4kMjY4dyd2KSWdci8kmMmYHN9i9NCcdQSLFT7doEvUZg2jl2l2AHwyss9a3UR_hyOVtEbk10Fg0cMCBNXk1EARGIeR5xnCUpH-i-L5GudqmhfCuIgv0azgQi4M4KeWZIqAhzyrewAPC-GFm_GN5tM50SUA0K8oTUQ_HyefmtiuxFQbnsDE1g8KuDt5Z0NPjKIdf10VtEuE-kFzxeUpudQog8Rut9Ws3Xt9a6b5fb8zbPIe2tuqKoXd5ZhqJIo2w8SxmrEXEU'

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      google:
        firebase: DEBUG

firebase:
  StorageBucketUrl: 'projectai-4361d.appspot.com'
  authUrl: 'https://identitytoolkit.googleapis.com/v1'
  authKey: 'AIzaSyDdro-Gy2WE7Xf1-capRrKNrU0pQdA0Gkg'

segmid:
  url: 'https://api.segmind.com'