spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

segmidToken: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDU3NTg1ODAsIm5iZiI6MTcwNTc1ODU4MCwianRpIjoiOTQxZjE2YjEtY2M5MS00NjQ2LWE2OGItYmYzMmRlYzY2ODNjIiwiZXhwIjoxNzA1ODQ0OTgwLCJpZGVudGl0eSI6InNocnV0aGlyZWRkeTE3MjlAZ21haWwuY29tIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.SVdwPuKzUVzBMAopESQGI8sX8zmGdaSdINY-rLQaj4fe---YzAu5bDVmgKb4D04LZyW6whuJFJeOZYj4AP8ONWa5KDklRq7Q-9W78wa8rCL9evOJMcHqmVAKjo-ltoBVHFnf-XgQ51rANLej5gHGD5NoIZV3NuS45ghNmmurg5fDMmTmfe1X1_WXrfZEpSqTVp3VMmKZ3l1eOx5nrK9KDULPHXbEPLeKWA-CT48onaibz62wd77oktlzEUXmyY0cmm2NuFxhtPjL-4hdUAu-4CRJfMvzS8LVwhEGAw7nQtgFybcTxZzl7T0hFuhrIryLmdeMvDE4O5WwpJw85mNFEq6r3kpiBUwX_mPbqHQdoCGwzWNtIf-dw93G7MALvoGtxEq0nyST1qHjCSj6kyA9difISCq1gC-c-cON6irhdOzn98CXtmdjpAv6c3xgVaXc7QK9U1L3Aa_aoJnUCh1Qzz3J-HNHjOOY5EW3bERO-L3byvF394oWFYcL_9b3r8Unxyi5iNj6d2PtXFp1rJ-w7GOXy2wIuHUihKSCzEt8NLX_VnJd_nmPoPPmR6GghfZU9U5Zyq3yO7lsTN0wAGNGOPs6kIDLKnxRCQ9QfN7lsFK5n5SgA0jZY4KEYXQw11FYI29Xx5ti0lCTIppqA6aZXc-Qt07NVLHQI5Eki9Ka5rU'

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      google:
        firebase: DEBUG