spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

segmidToken: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDYzNjIxNTEsIm5iZiI6MTcwNjM2MjE1MSwianRpIjoiNTY4ODczZTItMWNhYi00MWE5LWJlZTktMmU2NmFlNTdlMGJkIiwiZXhwIjoxNzA2NDQ4NTUxLCJpZGVudGl0eSI6InNocnV0aGlyZWRkeTE3MjlAZ21haWwuY29tIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.fprCWE8oCbpJ5acvk3DfJSpUEdt0D97a863TMhZ0nx4L8l96UC3F-beIawD7cbiN8Qukqus-0sZfiWJvDM_tUeij9P4kpud9HstevvcoDxk6GmmuS8d1TBArO0YpHaD3CIulan-NuBemEEiR9LmkaYxrogpX8Jmt-ubYV8_2czjomASBizj-YAYFaxylNyA6pNAn70QMEHb-ppuxcW-8gEpYeHpC6ZxfdgnzXFZFSIvjX-XlXIgUDh9LPBBaCuOsbeA4Uasfbdp_uIz-Lo-3vUNccq2MNb8QbBPKrsokqX353N31oqLi60MrJQbRN_CBWCmihBZWrpJ5rA2HO8B1GdyH4QIrmhMMU_M-QJLSkHcXp1Gy99EG3Y7asrkS1qTamwgPdlVFz0TboqKb7hyoPHwmToKOrE3dqrKLygivtAPEibed5je6zGv2c1MjiC5UGjpIiQzSvRlfs5XHiVc6zsqPo3mFtsYNGfcrMmtkmbZJ6UjqHR-rIbJ-U0SCB6Z8LDt6Eo5FpDAiXKgUa3whSfuBczpAREqX8Bw8wf4xG9w8cG73eLL01C-ZN_VGlm7fPQlr2H_cdYN1Zc5eOrik6ogKK1UcXVVjv32whSBoEb3owWVHfKuzUUDO2XAQFWUJXMZGQfZqkoIhHa8TuzFuXW4cGLNWyFZNyU9wMYghfc4'

logging:
  level:
    root: info
    com:
      google:
        firebase: info
  file:
    name: ../logs/springApp.log

firebase:
  StorageBucketUrl: 'projectai-4361d.appspot.com'
  authUrl: 'https://identitytoolkit.googleapis.com/v1'
  authKey: 'AIzaSyDdro-Gy2WE7Xf1-capRrKNrU0pQdA0Gkg'

segmid:
  url: 'https://api.segmind.com'
